### ISSUE TITLE
Google example broken?

### ISSUE THREAD

**Issue by tbsmark86** [babelouest/iddawc#6]
Hi, I can't get this to work in current form.

Only once I'am adding
   I_OPT_TOKEN_METHOD, I_TOKEN_AUTH_METHOD_SECRET_BASIC,
to the options.
Am I doing something wrong with my google client-id/secret or has google recently changed something?

**Comment by babelouest** [comment]
Hello,

For some reason, the google example stopped working as-is, because the client secret wasn't passed in the token request. I've added the option `I_OPT_TOKEN_METHOD, I_TOKEN_AUTH_METHOD_SECRET_BASIC,` to fix the problem and now it works again. I've updated the google example in the git repo.

I'll take a look to check if it's an iddawc issue or if google changed its oauth2 flow in a weird way.

Thanks for reporting the issue!
